name: make-puzzle-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: compile check
        run: |
          sudo apt -y install ocaml
          ocaml --version
          ocamlfind ocamlopt -o test -linkpkg test.ml
          ./test
