name: make-puzzle-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: compile check
        run: |
          sudo find /home/ -name "hoge.txt"   
          pwd
          cd /home
          ls
          cd /home/runner/work
          ls
          cd ci-test
          ls
          cd ci-test
          ls
          echo "これで終わり？"
#        run: docker run --rm -v $(pwd):/home/opam/satysfi amutake/satysfi satysfi --type-check-only /home/runner/work/make-puzzle/make-puzzle/test/test.saty
