name: ci-test

on: [push, pull_request]

jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest]
        ocaml-version: [ '4.09.0', '4.08.1', '4.07.1', '4.06.0' ]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam install xml-light
    - run: opam install menhir
    - run: cp ~/.opam/*/bin/menhir .
    - run: opam install ocamlfind
    - run: cp ~/.opam/*/bin/ocamlfind .
    - run: make xmltest
