name: ci-test

on: [push, pull_request]

jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: ['4.08.1']
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin add test.dev -n .
    - run: opam depext -yt test
    - run: opam install -t .
