name: ci-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: OCaml Install
        run: |
          sudo apt update
          sudo apt -y install ocaml=4.06.0
          ocaml --version
          ocamlfind ocamlopt --version
      - name: compile
        run: ocamlopt test.ml
      - name: test
        run: ./a.out
