name: ci-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: OCaml Install
        run: |
          sudo apt -y install ocaml
          ocaml --version
      - name: compile
        run: ocamlfind ocamlopt -o test -linkpkg test.ml
      - name: test
        run: ./test
