name: make-puzzle-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: compile check
        run: |
          sudo find /home/ -name "test.saty"   
          pwd
          cd /home
          ls
          cd /home/runner/work
          ls
          cd ci-test
          ls
          cd ci-test
          ls
          echo "これで終わり？"
          cat $(pwd)/test.saty
#          docker run --rm -v $(pwd):/home/opam/satysfi amutake/satysfi satysfi --type-check-only /home/runner/work/ci-test/ci-test/test/test.saty
